### ISSUE TITLE
cibuildwheel fails with missing libraries for musllinux 

### ISSUE THREAD

**Issue by LennyN95** [ImagingDataCommons/dcmqi-python-distributions#4]
The pypa/cibuildwheel@v2.16 (v2.16.5, v2.17) fails for Linux distributions using Musl (see screenshot).

<img width="1139" alt="Bildschirmfoto 2024-04-23 um 14 33 43" src="https://github.com/ImagingDataCommons/dcmqi-python-distributions/assets/14541510/c27d02fa-27e9-4109-899d-7e71313d4ba5">

@jcfr This is quite new for me and I heavily relied on your usage of the scientific python package template in the s5cmd project. Do you know what the best approach would be to target this issue? Any hint into the right direction is appreciated and likely will save me hours of try & error.

**Comment by LennyN95** [comment]
See action: https://github.com/ImagingDataCommons/dcmqi-python-distributions/actions/runs/8800019693

**Comment by jcfr** [comment]
Since the `s5cmd` excutables repackaged in the context of `s5cmd-python-distributions`[^1] are implemented in Go, they do not have any dependency on a specific C standard library implementation. This means that supporting musl and manylinux (glibc) was straightforward.

In the context of dcmqi, I suggest to exclude musl support at first.

[^1]: https://github.com/ImagingDataCommons/s5cmd-python-distributions?tab=readme-ov-file#platforms

**Comment by fedorov** [comment]
Thank you @jcfr! 🙏

**Comment by LennyN95** [comment]
Thank you, @jcfr. This helped a lot!!

I'll exclude musl support for now.
Implemented in 591cd41cad986927e0239b3eac4bb82b0eb047bb.
